{% set name = "spyndex" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5f1e4ebcd37e1baf40e9305019a4a9bc9552dfdf7ea6c542d9ed0d1f030bfcf0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - dask >=2021.9.1
    - earthengine-api
    - eemont >=0.2.5
    - matplotlib-base
    - numpy
    - pandas
    - python >=3.7
    - python-box
    - requests
    - seaborn
    - xarray

test:
  imports:
    - spyndex

about:
  home: https://github.com/davemlz/spyndex
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Awesome Spectral Indices in Python
  doc_url: https://spyndex.readthedocs.io/
  dev_url: https://github.com/davemlz/spyndex

extra:
  recipe-maintainers:
    - davemlz
