{% set name = "spyndex" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spyndex-{{ version }}.tar.gz
  sha256: 09e660d21ac065dca2d950adc67347fcb0e2d5e4439d02ea129ee35b10084445

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - dask-core >=2023.7.0
    - eemont >=0.3.6
    - matplotlib-base
    - pandas >=2.0.3
    - python-box >=6.0
    - requests
    - seaborn
    - xarray >=2023.6.0

test:
  imports:
    - spyndex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/awesome-spectral-indices/spyndex
  summary: Awesome Spectral Indices in Python
  license: MIT
  license_file: LICENSE
  doc_url: https://spyndex.readthedocs.io/
  dev_url: https://github.com//awesome-spectral-indices/spyndex

extra:
  recipe-maintainers:
    - davemlz
