{% set name = "spyndex" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 80cb3f3ed43abbdd0c67d9952131ba278daee5b000da5295839b72f8067e01c0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - dask >=2021.9.1
    - earthengine-api
    - eemont >=0.3.6
    - matplotlib-base
    - numpy
    - pandas
    - python >=3.7
    - python-box >=6.0
    - requests
    - seaborn
    - xarray

test:
  imports:
    - spyndex

about:
  home: https://github.com/awesome-spectral-indices/spyndex
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Awesome Spectral Indices in Python
  doc_url: https://spyndex.readthedocs.io/
  dev_url: https://github.com//awesome-spectral-indices/spyndex

extra:
  recipe-maintainers:
    - davemlz
