{% set name = "spyndex" %}
{% set version = "0.10.0" %}

package:
  name: spyndex
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/spyndex/spyndex-{{ version }}.tar.gz
  sha256: 039c3b9bd0b24613e03aa26b79a44aee677d6722c68c5dbed6686a833432e3e0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - wheel
    - pip
  run:
    - python >=3.8
    - dask-core >=2023.7.0
    - matplotlib-base
    - pandas >=2.0.3
    - pyarrow
    - python-box >=6.0
    - requests
    - seaborn
    - xarray >=2023.6.0

test:
  imports:
    - spyndex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/awesome-spectral-indices/spyndex
  summary: Awesome Spectral Indices in Python
  license: MIT
  license_file: LICENSE
  doc_url: https://spyndex.readthedocs.io/
  dev_url: https://github.com//awesome-spectral-indices/spyndex

extra:
  recipe-maintainers:
    - davemlz
