{% set name = "spyndex" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 137374e36c24ecbd76d6e23cb87afc004828727be0f74e171c399b8b85a31f17

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - dask >=2021.9.1
    - earthengine-api
    - eemont >=0.2.5
    - matplotlib-base
    - numpy
    - pandas
    - python >=3.7
    - python-box
    - requests
    - seaborn
    - xarray

test:
  imports:
    - spyndex

about:
  home: https://github.com/davemlz/spyndex
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Awesome Spectral Indices in Python
  doc_url: https://spyndex.readthedocs.io/
  dev_url: https://github.com/davemlz/spyndex

extra:
  recipe-maintainers:
    - davemlz
